CREATE TABLE USER_REGISTRATION_REQUEST (ID VARCHAR(36) PRIMARY KEY, USERNAME VARCHAR(255) NOT NULL UNIQUE, EMAIL VARCHAR(255) NOT NULL UNIQUE, PASSWORD VARCHAR(255) NOT NULL, STATUS VARCHAR(20) NOT NULL, CREATE_TIME TIMESTAMP NOT NULL, REQUEST_MESSAGE TEXT DEFAULT NULL, ADMIN_REMARK TEXT DEFAULT NULL);
CREATE INDEX IDX_USER_REGISTRATION_REQUEST_STATUS ON USER_REGISTRATION_REQUEST(STATUS);
CREATE INDEX IDX_USER_REGISTRATION_REQUEST_EMAIL ON USER_REGISTRATION_REQUEST(EMAIL);
CREATE INDEX IDX_USER_REGISTRATION_REQUEST_USERNAME ON USER_REGISTRATION_REQUEST(USERNAME); 